SELECT SUM(amount) AS total_payment_collected FROM payments;

SELECT 
	p.product_name, 
    SUM(oi.quantity * p.price) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN orders o On oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_name
ORDER BY total_revenue DESC;

-- “This query calculates total revenue generated by each product considering only
-- delivered orders, and ranks them in descending order to identify top-performing products.”